# The LB+WIF stack, in test.cru.org so it can share an org with a workforce pool.
project_id      = "cru-iap-e2e-lb"
project_number  = "898330966415"
organization_id = "000000000000"

subdomain = "cru-iap-wif"

# Borrow the keep-zero POC pool: same org, already ACTIVE, and already mapping
# google.email correctly (verified live). No new org-level resource, and no new
# Okta app -- its SAML app's ACS URL already embeds this pool id.
enable_workforce_federation  = true
shared_workforce_pool        = "locations/global/workforcePools/keepzero-okta-poc"
shared_workforce_provider_id = "okta-preview-saml"
okta_provider_type           = "saml"

# google.subject = assertion.subject = Okta NameID = the user's email.
iap_members = [
  "principal://iam.googleapis.com/locations/global/workforcePools/keepzero-okta-poc/subject/matt.drees@cru.org",
  # Scratch user, for the headless Playwright capture. Assigned to the
  # "Keep-Zero POC" Okta SAML app 2026-07-25 with Matt's approval.
  "principal://iam.googleapis.com/locations/global/workforcePools/keepzero-okta-poc/subject/cru-iap-e2e-test@example.invalid",
]

# Phase 2: generated by the API in phase 1 (see variables.tf).
wif_oauth_client_generated_id = "a98250eef-0b23-4dc1-b7ee-536041fc8b4c"

# echoserver dumps request headers into the response body, so a signed-in
# browser sees the real x-goog-iap-jwt-assertion and it can be fed straight
# into CruIap::TokenVerifier. Only reachable behind IAP.
container_image = "gcr.io/google-containers/echoserver:1.10"
